sdk additions, query delivery status functions
wormhole-foundation/trustless-generic-relayer pull request #79
Opened 2023-02-02 15:23 UTC by chase-45

2023-03-13 22:55 UTC, JoeHowarth requested changes

2023-03-13 22:55 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    return { type: -1, parsed: "Invalid wormhole message" }
Either throw here or return undefined

2023-03-13 22:55 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +export function printInfo(info: DeliveryInfo | RedeliveryInfo) {
I expect people to use this in app frontends, so can we split this into 2 functions: 1 that returns a string and a wrapping one that also prints it to the console

2023-03-13 22:55 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    if(!isChain(targetChain)) throw Error("Invalid Chain")
include the invalid chainId in the error

2023-03-13 22:55 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    const targetChainProvider =
This block of code has been repeated a few times - make a helper?

2023-03-13 22:55 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +/* [1]
What's up with this?

2023-03-14 16:05 UTC, derpy-duck commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +/* [1]
Ah this is old code that was SDK methods for getting status by Vaa hash instead of transaction hash. 

The problem with this is the contracts now don't have 'vaa hash' as an indexed parameter on the event; we had decided to remove this.

But yes I think it is correct to remove this comment; we can re-code this if we ever decide to do things by Vaa hash

2023-03-14 16:06 UTC, derpy-duck commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    const targetChainProvider =
Which block of code specifically?

2023-03-14 17:16 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    stringifiedInfo += (`Found Redelivery request in transaction ${info.redeliverySourceTransactionHash} on ${printChain(info.redeliverySourceChainId)}`)
This will not include line breaks between the statements like `console.log(...)` does. Probably want to put `+ os.EOL` after each

2023-03-14 17:16 UTC, JoeHowarth commented on relayer_engine/pkgs/sdk/src/main/status.ts
> +    const targetChainProvider =
Getting a provider or falling back to the default, then checking if it's null. It's not a big deal if you'd prefer to not create a helper
196-205 in the latest commit

2023-03-15 21:50 UTC, derpy-duck commented
ah nice catch @JoeHowarth  (the new lines).
Now it should be correct (tested it; can't share the image here for some reason)

also added the helper

2023-03-15 22:32 UTC, JoeHowarth approved these changes

2023-03-15 22:32 UTC, merged