Eliminates redundant `await`s.
wormhole-foundation/trustless-generic-relayer pull request #98
Opened 2023-02-17 13:46 UTC by scnale

2023-02-17 19:42 UTC, derpy-duck approved these changes
Looks good to me

2023-02-20 19:21 UTC, JoeHowarth requested changes

2023-02-20 19:21 UTC, JoeHowarth commented on relayer_engine/src/plugin/src/plugin.ts
> +          await relayProvider
Why should this await be removed? If we do so, then the following log line may fire when an error actually occurred here.

2023-02-20 19:21 UTC, JoeHowarth commented on relayer_engine/src/plugin/src/plugin.ts
> +        await relayProvider
Same as above

2023-02-20 19:34 UTC, scnale commented on relayer_engine/src/plugin/src/plugin.ts
> +          await relayProvider
Actually, this await is added :sweat_smile:. I wasn't sure if this was an intended dangling promise so I didn't want to merge this right away. Even if it is, I'd suggest adding a `.catch` to handle errors.

2023-02-21 17:45 UTC, JoeHowarth commented on relayer_engine/src/plugin/src/plugin.ts
> +          await relayProvider
Good catch! And here I thought I was using too many awaits hahah

Yeah let's merge this

2023-02-21 17:45 UTC, JoeHowarth approved these changes

2023-02-21 21:17 UTC, merged